USERID_FOR_MASSLOOKER = [
"soufiane___fit",
    "fitness_bdarija",
    "sergiconstance",
    "jeremy_buendia",
    "simeonpanda",
    "sadikhadzovic",
    "kaigreene",
    "philheath",
    "big_ramy",
    "jeff_seid",
    ]

USERID_FOR_INSHACKLE = [
"ulissesworld",
    "andreideiu_",
    "sergiconstance",
    "jeremy_buendia",
    "simeonpanda",
    "sadikhadzovic",
    "kaigreene",
    "philheath",
    "big_ramy",
    "jeff_seid",
    "tavicastro",
    "zacaynsley",
    "ryanjterry",
    "blessing_awodibu",
    "calumvonmoger",
    "lazar_angelov_official",
    "chanelcocobrown",
    "brandon__curry",
    "jaycutler",
    "martynfordofficial",
    ]
